// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function notAuthed() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}

// src/lib/mcp/tools/search-leads.ts
var search_leads_default = defineTool({
  name: "search_leads",
  title: "Search Google Maps leads",
  description: "Search leads captured from Google Maps for the signed-in user. Optional text filter matches company name, address or specialties.",
  inputSchema: {
    query: z.string().optional().describe("Text to match against company name/address/specialties."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    let q = sb.from("leads").select("id, nome_empresa, telefone, endereco, site, rating, especialidades, cnpj, disparo").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (query && query.trim()) {
      const like = `%${query.trim()}%`;
      q = q.or(
        `nome_empresa.ilike.${like},endereco.ilike.${like},especialidades.ilike.${like}`
      );
    }
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-linkedin-contacts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_linkedin_contacts_default = defineTool2({
  name: "search_linkedin_contacts",
  title: "Search LinkedIn contacts",
  description: "Search LinkedIn contacts prospected by the signed-in user. Optional filter matches name, position or company.",
  inputSchema: {
    query: z2.string().optional().describe("Text to match against name/cargo/empresa."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    let q = sb.from("linkedin_contacts").select("id, nome, cargo, empresa, localizacao, linkedin_url, email, telefone, cadencia_status, etapa_atual").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (query && query.trim()) {
      const like = `%${query.trim()}%`;
      q = q.or(`nome.ilike.${like},cargo.ilike.${like},empresa.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-instagram-contacts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_instagram_contacts_default = defineTool3({
  name: "search_instagram_contacts",
  title: "Search Instagram contacts",
  description: "Search Instagram contacts prospected by the signed-in user. Optional filter matches @username, name or bio.",
  inputSchema: {
    query: z3.string().optional().describe("Text to match against username/nome/bio."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    let q = sb.from("instagram_contacts").select("id, username, nome, bio, seguidores, whatsapp, email, site, profile_url, is_business").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (query && query.trim()) {
      const like = `%${query.trim()}%`;
      q = q.or(`username.ilike.${like},nome.ilike.${like},bio.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-pipeline-cards.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_pipeline_cards_default = defineTool4({
  name: "list_pipeline_cards",
  title: "List pipeline CRM cards",
  description: "List CRM pipeline cards for the signed-in user, optionally filtered by stage.",
  inputSchema: {
    estagio: z4.string().optional().describe("Pipeline stage to filter by."),
    limit: z4.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estagio, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    let q = sb.from("pipeline_cards").select("id, nome_empresa, contato, telefone, email, estagio, origem, valor_estimado, observacoes, proximo_followup_at, position").eq("user_id", ctx.getUserId()).order("position", { ascending: true }).limit(limit ?? 50);
    if (estagio) q = q.eq("estagio", estagio);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-pipeline-card.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var create_pipeline_card_default = defineTool5({
  name: "create_pipeline_card",
  title: "Create pipeline CRM card",
  description: "Create a new CRM pipeline card for the signed-in user. Use this to move a lead into the sales pipeline.",
  inputSchema: {
    nome_empresa: z5.string().min(1).describe("Company name."),
    contato: z5.string().optional().describe("Contact person name."),
    telefone: z5.string().optional().describe("Phone/WhatsApp."),
    email: z5.string().optional().describe("Contact email."),
    estagio: z5.string().optional().describe("Pipeline stage (default: first stage of the board)."),
    origem: z5.string().optional().describe("Where the lead came from (e.g. 'maps', 'linkedin', 'instagram')."),
    valor_estimado: z5.number().optional().describe("Estimated deal value."),
    observacoes: z5.string().optional().describe("Internal notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("pipeline_cards").insert({ ...input, user_id: ctx.getUserId() }).select().single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created card ${data.id} for ${data.nome_empresa}` }],
      structuredContent: { card: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jctfjyzqtlqehnapkjpc";
var mcp_default = defineMcp({
  name: "leadsbooster-mcp",
  title: "LeadsBooster",
  version: "0.1.0",
  instructions: "Access LeadsBooster prospecting data for the signed-in user. Use search_leads (Google Maps), search_linkedin_contacts and search_instagram_contacts to find prospects, list_pipeline_cards to inspect the sales CRM, and create_pipeline_card to promote a lead into the pipeline. All tools are scoped to the authenticated user's data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_leads_default,
    search_linkedin_contacts_default,
    search_instagram_contacts_default,
    list_pipeline_cards_default,
    create_pipeline_card_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
